name: invisimail_app
description: "Flutter client for InvisiMail backend"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0                # For API calls
  provider: ^6.0.5            # State management
  shared_preferences: ^2.2.2  # Store tokens locally
  flutter_secure_storage: ^9.0.0 # Secure JWT/Auth storage
  intl: ^0.19.0               # Date formatting
  cupertino_icons: ^1.0.8     # iOS icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
